version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: config/Dockerfile.api
    image: $DOCKER_USERNAME/breast-cancer-api:latest
    ports:
      - "5000:5000"

  streamlit_ui:
    build:
      context: ..
      dockerfile: config/Dockerfile.streamlit
    image: $DOCKER_USERNAME/breast-cancer-streamlit:latest
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:5000/predict
    depends_on:
      - api
