name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/breast-cancer-api:latest

    - name: Run container (for testing)
      run: docker run -d -p 5000:5000 --name breast-cancer-api-test ${{ secrets.DOCKER_USERNAME }}/breast-cancer-api:latest

    - name: Wait for API to be ready
      run: |
        sleep 10
        # Loop until the API health check responds successfully
        for i in $(seq 1 10); do
          if curl -s http://localhost:5000/; then
            echo "API is ready!"
            exit 0
          fi
          echo "Waiting for API... (Attempt $i)"
          sleep 5
        done
        echo "API did not become ready in time."
        exit 1

    - name: Test health endpoint
      run: curl http://localhost:5000/

    - name: Test prediction endpoint
      run: |
        # Create a sample payload for prediction
        cat <<EOF > payload.json
        {
          "radius_mean": 17.99,
          "texture_mean": 10.38,
          "perimeter_mean": 122.8,
          "area_mean": 1001.0,
          "smoothness_mean": 0.1184,
          "compactness_mean": 0.2776,
          "concavity_mean": 0.3001,
          "concave points_mean": 0.1471,
          "symmetry_mean": 0.2419,
          "fractal_dimension_mean": 0.07871,
          "radius_se": 1.095,
          "texture_se": 0.3568,
          "perimeter_se": 8.589,
          "area_se": 153.4,
          "smoothness_se": 0.006399,
          "compactness_se": 0.04904,
          "concavity_se": 0.05373,
          "concave points_se": 0.01587,
          "symmetry_se": 0.03003,
          "fractal_dimension_se": 0.006193,
          "radius_worst": 25.38,
          "texture_worst": 17.33,
          "perimeter_worst": 184.6,
          "area_worst": 2019.0,
          "smoothness_worst": 0.1622,
          "compactness_worst": 0.6656,
          "concavity_worst": 0.7119,
          "concave points_worst": 0.2654,
          "symmetry_worst": 0.4601,
          "fractal_dimension_worst": 0.1189
        }
        EOF
        curl -X POST -H "Content-Type: application/json" -d @payload.json http://localhost:5000/predict

    - name: Clean up Docker container
      if: always()
      run: docker rm -f breast-cancer-api-test
